version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ~/airflow/:/usr/local/airflow/dags
    webserver:
        image: puckel/docker-airflow-dev-r
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ~/airflow/dags/:/usr/local/airflow/dags
            - ~/project/sp3-platform-analytics/machine-learning/mlmanager/:/usr/local/mlmanager
            - ~/project/sp3-platform-analytics/machine-learning/mlmanager/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
